# Generated by Django 5.2.1 on 2025-06-03 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia_clinica', to='citas.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('procedimiento', 'Procedimiento'), ('cirugia', 'Cirugía')], default='procedimiento', max_length=15, verbose_name='Tipo de registro')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del procedimiento o cirugía')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones posteriores')),
                ('dentista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos_realizados', to=settings.AUTH_USER_MODEL)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='pacientes.historiaclinica')),
            ],
            options={
                'verbose_name': 'Procedimiento/Cirugía',
                'verbose_name_plural': 'Procedimientos y Cirugías',
                'ordering': ['-fecha'],
            },
        ),
    ]
