# Generated by Django 5.2.1 on 2025-05-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('dentista', 'Dentista'), ('recepcionista', 'Recepcionista'), ('paciente', 'Paciente'), ('laboratorio', 'Laboratorio')], default='paciente', max_length=20, verbose_name='Rol'),
        ),
    ]
